token='OTI2MTYzMjY5NTAzMjk5Njk1.G5xucN.PuTzzRakq3seI5BztyJhbeWgmG1214AP9lGNL8'
truth='https://api.truthordarebot.xyz/v1/truth'
dare='https://api.truthordarebot.xyz/v1/dare'
wyr='https://api.truthordarebot.xyz/v1/wyr'
nhie='https://api.truthordarebot.xyz/v1/nhie'
paranoia='https://api.truthordarebot.xyz/v1/paranoia'
footer='Bot created by Jzcob#2842 and Sezn#6554.'

host='na01-sql.pebblehost.com'
user='customer_249998_fuyu'
password='YyZdusOTR8sOw8fk0@ks'
db='customer_249998_fuyu'